// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Vj-A6Unojlu4ajGX3UMy7NgBejXjH6g',
    appId: '1:820605465127:android:ba5c52803e50126a989402',
    messagingSenderId: '820605465127',
    projectId: 'flutter-ai-playground-3bc50',
    storageBucket: 'flutter-ai-playground-3bc50.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7hUnJ0fWyaXaQDQecvxqTZwbI18cklro',
    appId: '1:820605465127:web:050215e4131059ec989402',
    messagingSenderId: '820605465127',
    projectId: 'flutter-ai-playground-3bc50',
    authDomain: 'flutter-ai-playground-3bc50.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-3bc50.firebasestorage.app',
  );
}
